name: PR Workflows

on: [pull_request]

jobs:
  # Build site to verify PR doesn't break anything
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Update Hugo Modules
        run: hugo mod tidy

      - name: Install Node modules
        run: |
          hugo mod npm pack
          npm ci

      - name: Build
        run: hugo --minify
